### ISSUE TITLE
No API key configured error

### ISSUE THREAD

**Issue by willsweat** [asciinema/asciinema.org#181]
Hi,

I'm getting this issue when the asciinema client attempts it's POST to the server:
```
Started POST "/api/asciicasts" for 1.2.3.4 at 2014-12-31 00:27:54 +0000
Processing by Api::AsciicastsController#create as HTML
  Parameters: {"asciicast"=>{"stdout"=>#<ActionDispatch::Http::UploadedFile:0x000000037ff578 @tempfile=#<Tempfile:/tmp/RackMultipart20141231-19265-wab8r2>, @original_filename="stdout", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"asciicast[stdout]\"; filename=\"stdout\"\r\nContent-Type: application/octet-stream\r\n">, "stdout_timing"=>#<ActionDispatch::Http::UploadedFile:0x000000037ff2a8 @tempfile=#<Tempfile:/tmp/RackMultipart20141231-19265-1xgfdok>, @original_filename="stdout.time", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"asciicast[stdout_timing]\"; filename=\"stdout.time\"\r\nContent-Type: application/octet-stream\r\n">, "meta"=>#<ActionDispatch::Http::UploadedFile:0x000000037fef10 @tempfile=#<Tempfile:/tmp/RackMultipart20141231-19265-udgwr8>, @original_filename="meta.json", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"asciicast[meta]\"; filename=\"meta.json\"\r\nContent-Type: application/octet-stream\r\n">}}
  User Load (0.5ms)  SELECT  "users".* FROM "users" INNER JOIN "api_tokens" ON "api_tokens"."user_id" = "users"."id" WHERE "api_tokens"."token" = 'f6158dd0-06e3-XXX-XXX-XXX'  ORDER BY "users"."id" ASC LIMIT 1
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "asciicasts" ("command", "created_at", "duration", "shell", "snapshot", "stdin_data", "stdin_timing", "stdout_data", "stdout_timing", "terminal_columns", "terminal_lines", "terminal_type", "title", "updated_at", "user_agent", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING "id"  [["command", "/bin/bash"], ["created_at", "2014-12-31 00:27:54.417111"], ["duration", 8.298678757], ["shell", "/bin/bash"], ["snapshot", nil], ["stdin_data", nil], ["stdin_timing", nil], ["stdout_data", "stdout"], ["stdout_timing", "stdout.time"], ["terminal_columns", 125], ["terminal_lines", 69], ["terminal_type", "xterm"], ["title", ""], ["updated_at", "2014-12-31 00:27:54.417111"], ["user_agent", "asciinema/0.9.9 gc/go1.4 linux-amd64"], ["user_id", 1]]
   (0.8ms)  COMMIT
  Asciicast Load (0.2ms)  SELECT  "asciicasts".* FROM "asciicasts"  WHERE "asciicasts"."id" = $1 LIMIT 1  [["id", 10]]
Completed 500 Internal Server Error in 137ms
end of file reached** [Bugsnag] No API key configured, couldn't notify

EOFError (end of file reached):
  app/models/terminal.rb:51:in `readline'
  app/models/terminal.rb:51:in `read_line'
  app/models/terminal.rb:18:in `snapshot'
  app/services/film.rb:13:in `snapshot_at'
  app/services/asciicast_snapshot_updater.rb:13:in `block in generate_snapshot'
  app/models/asciicast.rb:65:in `with_terminal'
  app/services/asciicast_snapshot_updater.rb:12:in `generate_snapshot'
  app/services/asciicast_snapshot_updater.rb:5:in `update'
  app/services/asciicast_processor.rb:4:in `process'
  app/workers/asciicast_worker.rb:7:in `perform'
  app/services/asciicast_creator.rb:7:in `create'
  app/controllers/api/asciicasts_controller.rb:9:in `create'


  Rendered /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (12.3ms)
```
On the client end, the only error is:
```
root@someserver:~# exit
~ Asciicast recording finished.
~ Press <Enter> to upload, <Ctrl-C> to cancel.

Error: HTTP status: 500 Internal Server Error
```

**Comment by willsweat** [comment]
Hi,

I've tried compiling from source and it's still the same error. I'm using Ubuntu server, using both precise (v12) and trusty (v14) as well as using the package from zanchey's repo. The interesting thing is that an older version (from September) seems to work ok.

I've tried using different ports and I'm not using a web proxy to redirect.

Thanks

**Comment by sickill** [comment]
I have just released 1.0. Can you try it? You need both latest cli and the website running the latest code.

**Comment by willsweat** [comment]
Hi Marcin,

I will try it this week and will let you know if I still have issues. Thank you for letting me know of the update!

_Will
